import "@/app/globals.css";

// Providers
import { Providers } from "@/app/providers";

// SEO
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body>
        <Providers>
          <div className="bg-[url('/img/wii-wallpaper.png')] bg-cover bg-no-repeat">
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
